# Generated by Django 5.2.1 on 2025-05-27 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_network_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.contact', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='network',
            name='level',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], editable=False, null=True, verbose_name='Уровень поставщика'),
        ),
        migrations.AlterField(
            model_name='network',
            name='products',
            field=models.ManyToManyField(to='network.product', verbose_name='Продукт'),
        ),
    ]
