# Generated by Django 5.2.1 on 2025-05-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_network_contact_alter_network_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Задолженность перед поставщиком'),
        ),
    ]
