# Generated by Django 5.2.1 on 2025-05-31 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_network_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.contact', verbose_name='Контакты'),
        ),
    ]
